repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: ty-check
        name: ty type check
        entry: ty check --exclude "tests/*"
        language: system
        pass_filenames: false
        types: [python]
