# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

lint.select = [
    "ALL", # include all the rules, including new ones
]

lint.ignore = [
    "ANN002",   # Missing type args
    "ANN003",   # Missing type kwargs
    "ASYNC210", # Blocking HTTP call in async function
    "COM812",
    # Missing docstring
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D202",
    "D203",    # Incorrect blank line before class
    "D212",    # Multi-line summary first line
    "E501",    # Line too long
    "EM101",
    "F405",    # Name may be undefined, or defined from star imports: <module>
    "FIX001",  # Line contains FIXME
    "FIX002",  # Line contains TODO
    "G004",
    "PERF203",
    "PLR2004",
    "PLR0913", # Too many arguments
    "TD001",   # Invalid TODO tag
    "TD002",   # Missing TODO author
    "TD003",   # Missing TODO link
    "TRY003",
]

[lint.per-file-ignores]
"tests/*.py" = ["S101"] # Use of assert detected
